yarnPath: .yarn/releases/yarn-3.2.2.cjs
nodeLinker: node-modules
# npmAuthIdent: ${NPM_USERNAME}:${NPM_PASSWORD}
# npmAuthToken: ${GITHUB_TOKEN}
# npmPublishAccess: 'public'
# npmAuditRegistry: 'https://npm.pkg.github.com'
